### ISSUE TITLE
"electron-dev-runner src/main/index.ts --vite" not working

### ISSUE THREAD

**Issue by joserick** [cyytemplate/vite-electron-ts#1]
Hi,

This repository not working in linux???
```bash
yarn run v1.22.10
$ electron-dev-runner src/main/index.ts --vite
fs.js:1521
    throw new ERR_FEATURE_UNAVAILABLE_ON_PLATFORM('watch recursively');
    ^

TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at Object.watch (fs.js:1521:11)
    at watchFile (/home/jose/Proyectos/xposbox/node_modules/electron-dev-runner/lib/index.js:22:6)
    at run (/home/jose/Proyectos/xposbox/node_modules/electron-dev-runner/lib/index.js:83:3)
    at Object.<anonymous> (/home/jose/Proyectos/xposbox/node_modules/electron-dev-runner/lib/bin.js:40:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_FEATURE_UNAVAILABLE_ON_PLATFORM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cyyjs** [comment]
Please try to update `electron-dev-runner` version to `1.0.1`
